### ISSUE TITLE
Configure Slack command fails

### ISSUE THREAD

**Issue by cameronoxley** [claudiajs/claudia-bot-builder#104]
Hi guys, 

When calling:

`claudia update --configure-slack-slash-command`

After successfully deploying the bot to AWS, I receive the following error:

```
loading Lambda config   lambda.setupRequestListeners
{ CredentialsError: Missing credentials in config
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/claudia/node_modules/aws-sdk/lib/http/node.js:83:34)
    at ClientRequest.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at Socket.emitTimeout (_http_client.js:630:10)
    at Socket.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:338:8)
    at ontimeout (timers.js:386:14)
  message: 'Missing credentials in config',
  code: 'CredentialsError',
  time: 2017-08-23T17:35:07.540Z,
  retryable: true,
  originalError:
   { message: 'Could not load credentials from any providers',
     code: 'CredentialsError',
     time: 2017-08-23T17:35:07.540Z,
     retryable: true,
     originalError:
      { message: 'Connection timed out after 1000ms',
        code: 'TimeoutError',
        time: 2017-08-23T17:35:07.539Z,
        retryable: true } } }
```

**Comment by iMacHumphries** [comment]
Try this:
pip install awscli
aws configure

**Comment by stojanovic** [comment]
Yeah, it looks like your credentials are not accessible.
Make sure you selected the right profile, ie. in hello world tutorial on Claudia.js website, we used "claudia" profile, so you would need to do: `claudia update --profile claudia`
